use map_data;
DROP TABLE `map_data`.`ndbc_observations`;
CREATE TABLE `ndbc_observations` (
  `station_id`  varchar(24) CHARACTER SET utf8 ,
  `year`  int(11),
  `month` int(11),
  `day` int(11),
  `hour` int(11),
  `minute` int(11),
  `lat` float,
  `lon` float,
  `wind_dir` int(11),
  `wind_speed` float,
  `gust` float,
  `wave_height` float,
  `mwd` int(11),
  `pressure` float,
  `ptdy`  float,
  `air_temp`  float,
  `water_temp`  float,
  `dewpoint`  float,
  `tide`  float,
  `vis`  float,
  `dpd`  int(11),
  `apd`  float,
  `obs_time` datetime,
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `timeIndex` (`obs_time`) USING BTREE
)  AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;